export const allProducts = {
  bandcamp: [
    {
      image: "/images/yacht.png",
      title: "Yacht",
      storeLabel: "OFFICIAL SITE",
      description: "A high-capacity power bank with fast charging support.",
      link: "/vendors/bandcamp/yacht",
      main_image: "/images/yacht.png",
      thumbnail_1: "/images/yacht.png",
      thumbnail_2: "/images/yacht.png",
      thumbnail_3: "/images/yacht.png",
    },
    {
      image: "/images/fracture.png",
      title: "Fracture",
      storeLabel: "OFFICIAL SITE",
      description: "The latest Xiaomi smartphone with cutting-edge features.",
      link: "/vendors/bandcamp/fracture",
      main_image: "/images/fracture.png",
      thumbnail_1: "/images/phone-thumb-1.png",
      thumbnail_2: "/images/phone-thumb-2.png",
      thumbnail_3: "/images/phone-thumb-3.png",
    },
    {
      image: "/images/strangelyIP.png",
      title: "A Strangely Isolated",
      storeLabel: "OFFICIAL SITE",
      description: "A powerful router with excellent connectivity and speed.",
      link: "/vendors/bandcamp/a-strangely-isolated",
      main_image: "/images/adapter-main.png",
      thumbnail_1: "/images/adapter-thumb-1.png",
      thumbnail_2: "/images/adapter-thumb-2.png",
      thumbnail_3: "/images/adapter-thumb-3.png",
    },
    {
      image: "/images/anthem.png",
      title: "International Anthem",
      storeLabel: "OFFICIAL SITE",
      description: "Wireless earbuds with superior sound quality and noise cancellation.",
      link: "/vendors/bandcamp/xiaomi-buds-4",
      main_image: "/images/earbuds-main.png",
      thumbnail_1: "/images/earbuds-thumb-1.png",
      thumbnail_2: "/images/earbuds-thumb-2.png",
      thumbnail_3: "/images/earbuds-thumb-3.png",
    },
    {
      image: "/images/kidsrouter.png",
      title: "The Get Up Kids Router",
      storeLabel: "OFFICIAL SITE",
      description: "A wireless car charger with fast charging capabilities.",
      link: "/vendors/bandcamp/xiaomi-50w-wireless-car-charger",
      main_image: "/images/wireless-car-charger-main.png",
      thumbnail_1: "/images/wireless-car-charger-thumb-1.png",
      thumbnail_2: "/images/wireless-car-charger-thumb-2.png",
      thumbnail_3: "/images/wireless-car-charger-thumb-3.png",
    },
    {
      image: "/images/banco.png",
      title: "Banco De Gaia",
      storeLabel: "OFFICIAL SITE",
      description: "A high-definition monitor with vibrant colors and wide viewing angles.",
      link: "/vendors/bandcamp/xiaomi-monitor",
      main_image: "/images/monitor-main.png",
      thumbnail_1: "/images/monitor-thumb-1.png",
      thumbnail_2: "/images/monitor-thumb-2.png",
      thumbnail_3: "/images/monitor-thumb-3.png",
    },
    {
      image: "/images/pete.png",
      title: "Pete Yorn",
      storeLabel: "OFFICIAL SITE",
      description: "An adjustable monitor light to reduce eye strain.",
      link: "/vendors/bandcamp/xiaomi-monitor-light",
      main_image: "/images/monitor-light-main.png",
      thumbnail_1: "/images/monitor-light-thumb-1.png",
      thumbnail_2: "/images/monitor-light-thumb-2.png",
      thumbnail_3: "/images/monitor-light-thumb-3.png",
    },
    {
      image: "/images/dozen.png",
      title: "Party Dozen",
      storeLabel: "OFFICIAL SITE",
      description: "A stylish smartwatch with fitness tracking features.",
      link: "/vendors/bandcamp/xiaomi-watch",
      main_image: "/images/watch-main.png",
      thumbnail_1: "/images/watch-thumb-1.png",
      thumbnail_2: "/images/watch-thumb-2.png",
      thumbnail_3: "/images/watch-thumb-3.png",
    },
    {
      image: "/images/mtlove.png",
      title: "More To Love by Salmon Brothers",
      storeLabel: "OFFICIAL SITE",
      description:
        "The Mi Band 3 is a budget-friendly fitness tracker featuring a sleek, water-resistant design with an OLED touchscreen display. It tracks your daily steps, heart rate, sleep patterns, and more, while offering up to 20 days of battery life on a single charge.",
      link: "/vendors/bandcamp/xiaomi-mi-band-3",
      main_image: "/images/miband-main.png",
      thumbnail_1: "/images/miband-thumb-1.png",
      thumbnail_2: "/images/miband-thumb-2.png",
      thumbnail_3: "/images/miband-thumb-3.png",
    },
    {
      image: "/images/patio.png",
      title: "Patio User Manual by Etelin",
      storeLabel: "OFFICIAL SITE",
      description: "A precision stylus for drawing and note-taking.",
      link: "/vendors/bandcamp/xiaomi-stylus",
      main_image: "/images/patio.png",
      thumbnail_1: "/images/stylus-thumb-1.png",
      thumbnail_2: "/images/stylus-thumb-2.png",
      thumbnail_3: "/images/stylus-thumb-3.png",
    },
  ],
};
