export const allProducts = {
  bandcamp: [
    {
      image: "/images/yacht.png",
      title: "Yacht",
      storeLabel: "OFFICIAL SITE",
      description: "An engaging guide to mastering technology for the modern entrepreneur.",
      link: "/vendors/bandcamp/yacht",
      main_image: "/images/yacht2.jpg",
      thumbnail_1: "/images/yacht1.jpg",
      thumbnail_2: "/images/yacht2.jpg",
      thumbnail_3: "/images/yacht3.jpg",
    },
    {
      image: "/images/fracture.png",
      title: "Fracture",
      storeLabel: "OFFICIAL SITE",
      description: "A thrilling sci-fi novel exploring the boundaries of human consciousness.",
      link: "/vendors/bandcamp/fracture",
      main_image: "/images/fracture.png",
      thumbnail_1: "/images/fracture.png",
      thumbnail_2: "/images/fracture.png",
      thumbnail_3: "/images/fracture.png",
    },
    {
      image: "/images/strangelyIP.png",
      title: "A Strangely Isolated",
      storeLabel: "OFFICIAL SITE",
      description: "A thought-provoking collection of essays on isolation in the digital age.",
      link: "/vendors/bandcamp/a-strangely-isolated",
      main_image: "/images/strangelyIP.png",
      thumbnail_1: "/images/strangelyIP.png",
      thumbnail_2: "/images/strangelyIP.png",
      thumbnail_3: "/images/strangelyIP.png",
    },
    {
      image: "/images/anthem.png",
      title: "International Anthem",
      storeLabel: "OFFICIAL SITE",
      description: "An in-depth exploration of global music cultures and their influence.",
      link: "/vendors/bandcamp/international-anthem",
      main_image: "/images/anthem.png",
      thumbnail_1: "/images/anthem.png",
      thumbnail_2: "/images/anthem.png",
      thumbnail_3: "/images/anthem.png",
    },
    {
      image: "/images/kidsrouter.png",
      title: "The Get Up Kids Router",
      storeLabel: "OFFICIAL SITE",
      description: "A nostalgic journey through the punk rock scene of the early 2000s.",
      link: "/vendors/bandcamp/the-get-up-kids-router",
      main_image: "/images/kidsrouter.png",
      thumbnail_1: "/images/kidsrouter.png",
      thumbnail_2: "/images/kidsrouter.png",
      thumbnail_3: "/images/kidsrouter.png",
    },
    {
      image: "/images/banco.png",
      title: "Banco De Gaia",
      storeLabel: "OFFICIAL SITE",
      description: "A comprehensive guide to understanding world music genres.",
      link: "/vendors/bandcamp/banco-de-gaia",
      main_image: "/images/banco.png",
      thumbnail_1: "/images/banco.png",
      thumbnail_2: "/images/banco.png",
      thumbnail_3: "/images/banco.png",
    },
    {
      image: "/images/pete.png",
      title: "Pete Yorn",
      storeLabel: "OFFICIAL SITE",
      description: "An intimate memoir by the singer-songwriter Pete Yorn.",
      link: "/vendors/bandcamp/pete-yorn",
      main_image: "/images/pete.png",
      thumbnail_1: "/images/pete.png",
      thumbnail_2: "/images/pete.png",
      thumbnail_3: "/images/pete.png",
    },
    {
      image: "/images/dozen.png",
      title: "Party Dozen",
      storeLabel: "OFFICIAL SITE",
      description: "A guide to throwing unforgettable parties and events.",
      link: "/vendors/bandcamp/party-dozen",
      main_image: "/images/dozen.png",
      thumbnail_1: "/images/dozen.png",
      thumbnail_2: "/images/dozen.png",
      thumbnail_3: "/images/dozen.png",
    },
    {
      image: "/images/mtlove.png",
      title: "More To Love by Salmon Brothers",
      storeLabel: "OFFICIAL SITE",
      description:
        "A heartfelt story about family, love, and the complexities of sibling relationships.",
      link: "/vendors/bandcamp/more-to-love-by-salmon-brothers",
      main_image: "/images/mtlove.png",
      thumbnail_1: "/images/mtlove.png",
      thumbnail_2: "/images/mtlove.png",
      thumbnail_3: "/images/mtlove.png",
    },
    {
      image: "/images/patio.png",
      title: "Patio User Manual by Etelin",
      storeLabel: "OFFICIAL SITE",
      description: "A quirky guide to DIY patio projects and outdoor living spaces.",
      link: "/vendors/bandcamp/patio-user-manual-by-etelin",
      main_image: "/images/patio.png",
      thumbnail_1: "/images/patio.png",
      thumbnail_2: "/images/patio.png",
      thumbnail_3: "/images/patio.png",
    },
  ],
};
