export const allProducts = {
  xiaomi: [
    {
      image: "/images/pwbank.png",
      title: "Xiaomi Mi 50W Power Bank",
      storeLabel: "OFFICIAL STORE",
      description: "A high-capacity power bank with fast charging support.",
      link: "/vendors/xiaomi/xiaomi-mi-50w-power-bank",
      main_image: "/images/pwbank-main.png",
      thumbnail_1: "/images/pwbank-thumb-1.png",
      thumbnail_2: "/images/pwbank-thumb-2.png",
      thumbnail_3: "/images/pwbank-thumb-3.png",
    },
    {
      image: "/images/phone.png",
      title: "Xiaomi 14",
      storeLabel: "OFFICIAL STORE",
      description: "The latest Xiaomi smartphone with cutting-edge features.",
      link: "/vendors/xiaomi/xiaomi-14",
      main_image: "/images/phone-main.png",
      thumbnail_1: "/images/phone-thumb-1.png",
      thumbnail_2: "/images/phone-thumb-2.png",
      thumbnail_3: "/images/phone-thumb-3.png",
    },
    {
      image: "/images/adapter.png",
      title: "Xiaomi Router",
      storeLabel: "OFFICIAL STORE",
      description: "A powerful router with excellent connectivity and speed.",
      link: "/vendors/xiaomi/xiaomi-router",
      main_image: "/images/adapter-main.png",
      thumbnail_1: "/images/adapter-thumb-1.png",
      thumbnail_2: "/images/adapter-thumb-2.png",
      thumbnail_3: "/images/adapter-thumb-3.png",
    },
    {
      image: "/images/earbuds.png",
      title: "Xiaomi Buds 4",
      storeLabel: "OFFICIAL STORE",
      description: "Wireless earbuds with superior sound quality and noise cancellation.",
      link: "/vendors/xiaomi/xiaomi-buds-4",
      main_image: "/images/earbuds-main.png",
      thumbnail_1: "/images/earbuds-thumb-1.png",
      thumbnail_2: "/images/earbuds-thumb-2.png",
      thumbnail_3: "/images/earbuds-thumb-3.png",
    },
    {
      image: "/images/wireless-car-charger.png",
      title: "Xiaomi 50W Wireless Car Charger",
      storeLabel: "OFFICIAL STORE",
      description: "A wireless car charger with fast charging capabilities.",
      link: "/vendors/xiaomi/xiaomi-50w-wireless-car-charger",
      main_image: "/images/wireless-car-charger-main.png",
      thumbnail_1: "/images/wireless-car-charger-thumb-1.png",
      thumbnail_2: "/images/wireless-car-charger-thumb-2.png",
      thumbnail_3: "/images/wireless-car-charger-thumb-3.png",
    },
    {
      image: "/images/monitor.png",
      title: "Xiaomi Monitor",
      storeLabel: "OFFICIAL STORE",
      description: "A high-definition monitor with vibrant colors and wide viewing angles.",
      link: "/vendors/xiaomi/xiaomi-monitor",
      main_image: "/images/monitor-main.png",
      thumbnail_1: "/images/monitor-thumb-1.png",
      thumbnail_2: "/images/monitor-thumb-2.png",
      thumbnail_3: "/images/monitor-thumb-3.png",
    },
    {
      image: "/images/monitor-light.png",
      title: "Xiaomi Monitor Light",
      storeLabel: "OFFICIAL STORE",
      description: "An adjustable monitor light to reduce eye strain.",
      link: "/vendors/xiaomi/xiaomi-monitor-light",
      main_image: "/images/monitor-light-main.png",
      thumbnail_1: "/images/monitor-light-thumb-1.png",
      thumbnail_2: "/images/monitor-light-thumb-2.png",
      thumbnail_3: "/images/monitor-light-thumb-3.png",
    },
    {
      image: "/images/watch.png",
      title: "Xiaomi Watch",
      storeLabel: "OFFICIAL STORE",
      description: "A stylish smartwatch with fitness tracking features.",
      link: "/vendors/xiaomi/xiaomi-watch",
      main_image: "/images/watch-main.png",
      thumbnail_1: "/images/watch-thumb-1.png",
      thumbnail_2: "/images/watch-thumb-2.png",
      thumbnail_3: "/images/watch-thumb-3.png",
    },
    {
      image: "/images/miband.png",
      title: "Xiaomi Mi Band 3",
      storeLabel: "OFFICIAL STORE",
      description:
        "The Mi Band 3 is a budget-friendly fitness tracker featuring a sleek, water-resistant design with an OLED touchscreen display. It tracks your daily steps, heart rate, sleep patterns, and more, while offering up to 20 days of battery life on a single charge.",
      link: "/vendors/xiaomi/xiaomi-mi-band-3",
      main_image: "/images/miband-main.png",
      thumbnail_1: "/images/miband-thumb-1.png",
      thumbnail_2: "/images/miband-thumb-2.png",
      thumbnail_3: "/images/miband-thumb-3.png",
    },
    {
      image: "/images/stylus.png",
      title: "Xiaomi Stylus",
      storeLabel: "OFFICIAL STORE",
      description: "A precision stylus for drawing and note-taking.",
      link: "/vendors/xiaomi/xiaomi-stylus",
      main_image: "/images/stylus-main.png",
      thumbnail_1: "/images/stylus-thumb-1.png",
      thumbnail_2: "/images/stylus-thumb-2.png",
      thumbnail_3: "/images/stylus-thumb-3.png",
    },
  ],
};
